### ISSUE TITLE
cmd 'git log --oneline |less' problem

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#47]
@halfbrained 
1- it gievs list of lines bigger than current Term-plugin height. so 3-8 lines (with colored prompt) are scrolled away

![Screenshot from 2021-02-23 12-01-27](https://user-images.githubusercontent.com/4154978/108821675-035c6900-75cf-11eb-968b-d62ec253903a.png)

after UP arrow presses it shows top of log

![Screenshot from 2021-02-23 12-01-31](https://user-images.githubusercontent.com/4154978/108821687-06575980-75cf-11eb-9128-c3925b298552.png)

2- can we post "scroll down" command to "less" here if we see last line `:` ?

**Comment by halfbrained** [comment]
1- Now virtual terminal is always just 24 lines high. So less prints that many lines. A suggestion:

Add an option for terminal height. Constant value or same as memo height.   
(Always auto is not a good option because: terminal height can only be changed first opening, so if memo is small at start, and then resized larger, `less` will still think it is small)

2- wrote about this here https://github.com/halfbrained/cuda_terminal_plus/issues/46#issuecomment-784047998

**Comment by Alexey-T** [comment]
>Add an option for terminal height. Constant value or same as memo height.

yes, option for fixed height is OK, with default of 24 lines.
due to resizes, opt "as memo" is not good.

**Comment by halfbrained** [comment]
height option added (275df245fa506f75f6378b6b472e5136bb0f8095)

**Comment by Alexey-T** [comment]
great ! thank you.
