### ISSUE TITLE
macOS 10.11 - ls command shows crap

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#57]
![Снимок экрана 2021-03-03 в 20 49 19](https://user-images.githubusercontent.com/4154978/109849263-3bfce200-7c62-11eb-8251-e5b119d5845d.png)

**Comment by Alexey-T** [comment]
filenames overlap each other. 
but commands "uname -a" and "pwd" give ok result.

**Comment by halfbrained** [comment]
Fixed (0e426c0c8ad45e4bb5d36a2544bfa3dc90703d99, 927dde9045692197c6d7fce999dc3cc12049756b)

tab-characters were the reason for overlapping, fixed it.

Text is not colored because that is default on macos, but colors are still supported

![macls](https://user-images.githubusercontent.com/74829192/109975827-baf62700-7d03-11eb-8291-112cb021d01d.png)

Should I change default plugin's shell from bash to zsh on macos? It subtly hinting that it is the default  ^

**Comment by Alexey-T** [comment]
it's only for macOS Catalina!

Apple unveiled macOS Catalina yesterday with support for iPad apps and lots of new features, but a big change for developers and power users was missing from the on stage presentation. Starting with macOS Catalina, Macs will now use zsh as the default login shell and interactive shell across the operating system. 

so we must use bash for old os.
